name: Deploy Private GitHub repository to cPanel
on: 
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: horilla.westhubict.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps  # Use secure FTP
          port: 21
          local-dir: ./  # Sync everything from the root directory
          server-dir: /horilla/  # Ensure this is the correct path on cPanel